export const ACTIVE_IPC_CHANNELS = [
  'ia.configuracao.obter',
  'ia.configuracao.salvar',
  'ia.configuracao.testar',
  'ia.chat.enviar',
  'ia.conversas.listar',
  'ia.conversas.obter',
  'ia.conversas.criar',
  'ia.conversas.renomear',
  'ia.conversas.arquivar',
  'ia.conversas.restaurar',
  'ia.conversas.deletar',
  'ia.conversas.arquivarTodas',
  'ia.conversas.deletarArquivadas',
  'ia.mensagens.salvar',
  'ia.mensagens.atualizar',
  'ia.mensagens.deletarApos',
  'knowledge.stats',
  'knowledge.document.get',
  'knowledge.document.save',
  'knowledge.document.versions',
  'knowledge.document.restore',
  'knowledge.document.exportMarkdown',
  'knowledge.escolherArquivo',
  'knowledge.escolherPasta',
  'knowledge.bulkImport.start',
  'knowledge.removerFonte',
  'knowledge.toggleAtivo',
  'knowledge.obterTextoOriginal',
  'knowledge.extrairTexto',
  'knowledge.metadataStatus',
  'knowledge.gerarMetadataIa',
  'knowledge.importarCompleto',
  'knowledge.enrich',
  'knowledge.enrichmentConfig.get',
  'knowledge.enrichmentConfig.save',
  'knowledge.enrichmentModels.list',
  'knowledge.rebuildGraph',
  'knowledge.graphStats',
  'knowledge.search',
  'knowledge.graphData',
  'knowledge.graph.nodeEvidence',
  'knowledge.graphExplore',
  'protocolos.listar',
  'protocolos.salvar',
  'protocolos.duplicar',
  'protocolos.arquivar',
  'protocolos.restaurar',
  'protocolos.restaurarFixture',
  'jobs.list',
  'jobs.get',
  'jobs.cancel',
  'jobs.pause',
  'jobs.resume',
  'app:version',
] as const

export type ActiveIpcChannel = (typeof ACTIVE_IPC_CHANNELS)[number]

const ACTIVE_IPC_CHANNEL_SET = new Set<string>(ACTIVE_IPC_CHANNELS)

export function isActiveIpcChannel(channel: unknown): channel is ActiveIpcChannel {
  return typeof channel === 'string' && ACTIVE_IPC_CHANNEL_SET.has(channel)
}
